# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidadetecnica', models.IntegerField()),
                ('inovacao', models.IntegerField()),
                ('resultados', models.IntegerField()),
                ('metodologia', models.IntegerField()),
                ('adequacaoTematica', models.IntegerField()),
                ('media', models.CharField(max_length=30, null=True)),
                ('artigoAvaliacao', models.ManyToManyField(to='eventos.ArtigoCientifico')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('eventoPrincipal', models.CharField(max_length=30, null=True)),
                ('sigla', models.CharField(max_length=10, null=True)),
                ('dataEHoraDeInicio', models.DateTimeField(null=True)),
                ('logoTipo', models.CharField(max_length=200, null=True)),
                ('cidade', models.CharField(max_length=30, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('curriculo', models.CharField(max_length=100, null=True)),
            ],
            bases=('eventos.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Evento')),
                ('issn', models.CharField(max_length=30, null=True)),
            ],
            bases=('eventos.evento',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('cpf', models.CharField(max_length=11, null=True)),
            ],
            bases=('eventos.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoasJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('cnpj', models.CharField(max_length=12, null=True)),
                ('razaoSocial', models.CharField(max_length=100, null=True)),
            ],
            bases=('eventos.pessoa',),
        ),
        migrations.AddField(
            model_name='evento',
            name='realisador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Pessoa'),
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.PessoaFisica')),
                ('formacao', models.CharField(max_length=50, null=True, verbose_name=b'formacao')),
            ],
            bases=('eventos.pessoafisica',),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(null=True, to='eventos.Autor'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventoCientifico', to='eventos.EventoCientifico'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Avaliador'),
        ),
    ]
