# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='qualidadetecnica',
        ),
    ]
